name: "Comment run"
on:
  issue_comment:
    types: 
      - created

jobs:
  comment-run:
    if: contains(github.event.comment.body, 'RUN_TESTS')
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest]
        python: ['3.10']
    name: robot-browserstack-repo ${{ matrix.python }} - ${{ matrix.os }}
    env:
      BROWSERSTACK_USERNAME: ${{ secrets.BROWSERSTACK_USERNAME }}
      BROWSERSTACK_ACCESS_KEY: ${{ secrets.BROWSERSTACK_ACCESS_KEY }}
    steps:
      - uses: actions/checkout@v3
      - name: Setup python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python }}
      - name: Print python version
        run: python --version
      - name: Install dependencies
        run: python -m pip install -r requirements.txt
      - name: Print browserstack-sdk version
        run: browserstack-sdk --version
      - name: run tests in parallel
        run: browserstack-sdk robot ./tests/parallel/*.robot
      - name: run local tests in parallel
        run: browserstack-sdk robot ./tests/LocalTest.robot
